.scalafmt.conf, build.sbt, src/main/scala/org/virtuslab/internal/YamlError.scala, src/main/scala/org/virtuslab/internal/load/compose/Composer.scala, src/main/scala/org/virtuslab/internal/load/compose/Node.scala, src/main/scala/org/virtuslab/internal/load/compose/NodeTransform.scala, src/main/scala/org/virtuslab/internal/load/compose/NodeTransformer.scala, src/main/scala/org/virtuslab/internal/load/parse/Event.scala, src/main/scala/org/virtuslab/internal/load/parse/ParserImpl.scala, src/main/scala/org/virtuslab/internal/load/parse/ParserState.scala, src/main/scala/org/virtuslab/yaml/YamlDecoder.scala, src/main/scala/org/virtuslab/yaml/yaml.scala, src/test/scala/org/virtuslab/internal/load/compose/ComposerSpec.scala
Implementation of [compose phase](https://yaml.org/spec/1.2/spec.html#id2762107).  
The composer task is to produce a node graph (think of it as a JSON AST) from a stream of events. At now it's a very straightforward implementation that doesn't take into account any metadata information (because Tokens don't have it too), but this will change with improvements of the parser stage.  
Also, error handling is not the best one, but I think it's good enough for the first iteration.
=> Composer init

tests/test-core/shared/src/main/scala/org/virtuslab/yaml/ConfigTestRunner.scala, tests/test-core/shared/src/main/scala/org/virtuslab/yaml/TestSuiteRunner.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/Yaml.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/internal/load/parse/Parser.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/internal/load/parse/ParserImpl.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/internal/load/parse/CommentSpec.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/internal/load/parse/DocumentStartEndSpec.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/internal/load/parse/MappingSpec.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/internal/load/parse/ParserSpec.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/internal/load/parse/ScalarSpec.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/internal/load/parse/SequenceSpec.scala
Implements `getNextEvent` mentioned in https://github.com/VirtusLab/scala-yaml/issues/69
=> Add incremental processing for parsed events

yaml/shared/src/main/scala/org/virtuslab/yaml/internal/load/parse/ParserImpl.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/internal/load/reader/Tokenizer.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/internal/load/reader/token/Token.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/parser/MappingSuite.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/parser/SequenceSuite.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/tokenizer/TokenizerSuite.scala
Generate comma tokens, they are used to separated flow entries in flow collections. Flow collections are just an enhanced JSON syntax so most of the constructs are pretty straightforward. 
Moreover, in sequence you can use single mapping shorthand syntax - `[key: value]` instead of `[{key: pair}]
=> Add more support for flow collections

tests/test-suite/jvm/src/it/scala/org/virtuslab/yaml/YamlRunnerSpec.scala, tests/test-suite/jvm/src/main/scala/org/virtuslab/yaml/TestRunner.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/internal/dump/present/PresenterImpl.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/internal/load/compose/Composer.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/internal/load/parse/Event.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/internal/load/parse/ParserImpl.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/internal/load/reader/Tokenizer.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/internal/load/reader/token/Token.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/decoder/PrimitiveDecoderSuite.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/parser/AnchorSpec.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/parser/BaseParseSuite.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/parser/MappingSuite.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/parser/SequenceSuite.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/tokenizer/TokenizerSuite.scala
We still cannot parse anchor when a node is mapping key at the same time (require tokenizer changes from #87). Otherwise, it should just work. 
Follow-up: Handle anchors & aliases when composing nodes https://github.com/VirtusLab/scala-yaml/issues/88
=> Parsing anchors & aliases

tests/test-suite/jvm/src/main/scala/org/virtuslab/yaml/TestRunner.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/LoadSettings.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/Node.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/Tag.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/Yaml.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/YamlCodec.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/YamlDecoder.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/YamlEncoder.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/YamlError.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/internal/dump/serialize/SerializerImpl.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/internal/load/compose/Composer.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/internal/load/parse/Event.scala, yaml/shared/src/main/scala/org/virtuslab/yaml/internal/load/parse/ParserImpl.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/ComposerSuite.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/ConstructSuite.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/decoder/DecoderErrorsSuite.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/decoder/DecoderSuite.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/parser/AnchorSpec.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/parser/MappingSuite.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/parser/TagSuite.scala, yaml/shared/src/test/scala/org/virtuslab/yaml/tokenizer/TagSuite.scala
Each YAML node except its kind (scalar, mapping, sequence) has also a tag. Tag property indicates the type that the application should use to represent a given node. Typically, most tags are not explicitly specified in the character stream so YAML processor has to resolve them on its own using some schema. Recommended done is [core schema](https://yaml.org/spec/1.2.2/#core-schema).
=> Add tags to nodes

build.sbt
I don't know why, but there are artifacts for 2.12 at the Maven Central repository - https://mvnrepository.com/artifact/org.virtuslab/scala-yaml.
Indeed, `publishLocal` was publishing artifacts for 2.12 too. 
Setting `scalaVersion := scala3Version` in `inThisBuild` fixed this issue.
=> Do not publish for 2.12

core/shared/src/main/scala/org/virtuslab/yaml/YamlDecoder.scala, core/shared/src/test/scala/org/virtuslab/yaml/decoder/DecoderSuite.scala
closes https://github.com/VirtusLab/scala-yaml/issues/121
=> Fix `Option` parsing

.github/workflows/ci.yml, build.sbt, core/shared/src/main/scala-3/org/virtuslab/yaml/YamlDecoderCrossCompat.scala, core/shared/src/main/scala-3/org/virtuslab/yaml/YamlEncoderCrossCompat.scala, project/BuildHelper.scala, project/plugin.sbt
Additionally, fix errors on ~older~ Scala 3
I was hitting the following errors:
```scala
[error] -- Error: /Users/velvetbaldmime/projects/scala-yaml/core/shared/src/test/scala-3/org/virtuslab/yaml/BaseYamlEncoderSuite.scala:28:54
[error] 28 |    case class Data(int: Int, double: Double) derives YamlCodec
[error]    |                                                      ^
[error]    |undefined: YamlEncoderCrossCompanionCompat_this.deriveProduct # -1: TermRef(TermRef(NoPrefix,val YamlEncoderCrossCompanionCompat_this),deriveProduct) at inlining
[error]    |---------------------------------------------------------------------------
[error]    |Inline stack trace
[error]    |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]    |This location contains code that …
```
=> Reenable Scala 3 Native build, drop to Scala 3.1.3

build.sbt, project/BuildHelper.scala, project/Deps.scala, project/plugin.sbt
- use libraries from `Deps.scala`
- bump local snapshot version
- add pprint conditionally on local machines to dependencies
- add spacing between sbt plugins, otherwise Github is unable to resolve conflicts
=> build: minor tweaks

build.sbt, project/plugin.sbt
Pretty sure this fixes https://github.com/VirtusLab/scala-yaml/issues/177. The (empty) root project was being published with the same name as the core module, causing it to overwrite with an empty jar.
=> No-publish the root

core/shared/src/main/scala/org/virtuslab/yaml/Range.scala, core/shared/src/main/scala/org/virtuslab/yaml/YamlError.scala, core/shared/src/main/scala/org/virtuslab/yaml/internal/load/reader/ReaderCtx.scala, core/shared/src/main/scala/org/virtuslab/yaml/internal/load/reader/Tokenizer.scala, core/shared/src/test/scala/org/virtuslab/yaml/parser/MappingSuite.scala, core/shared/src/test/scala/org/virtuslab/yaml/parser/TagSuite.scala
fixes https://github.com/VirtusLab/scala-yaml/issues/160
=> Do not accept invalid sequence as mapping value

core/shared/src/main/scala/org/virtuslab/yaml/Yaml.scala, core/shared/src/main/scala/org/virtuslab/yaml/internal/load/compose/Composer.scala, core/shared/src/main/scala/org/virtuslab/yaml/internal/load/reader/Reader.scala, core/shared/src/main/scala/org/virtuslab/yaml/internal/load/reader/Tokenizer.scala, core/shared/src/main/scala/org/virtuslab/yaml/internal/load/reader/TokenizerContext.scala, core/shared/src/main/scala/org/virtuslab/yaml/internal/load/reader/token/BlockChompingIndicator.scala, core/shared/src/main/scala/org/virtuslab/yaml/internal/load/reader/token/Token.scala, core/shared/src/test/scala/org/virtuslab/yaml/BaseYamlSuite.scala, core/shared/src/test/scala/org/virtuslab/yaml/tokenizer/TagSuite.scala, core/shared/src/test/scala/org/virtuslab/yaml/tokenizer/TokenizerSuite.scala, core/shared/src/test/scala/org/virtuslab/yaml/traverse/NodeVisitorSuite.scala, integration-tests/src/main/scala/org/virtuslab/yaml/TestRunner.scala
Main change - return [null character](https://www.ascii-code.com/0) instead of None in reader and tokenizer. I'm planning to make tokenizer less magical (well, other parts of code too) and I found wrapping with Some more difficult to comprehend than just operating on plain chars
=> small tweaks in tokenizer

core/shared/src/main/scala/org/virtuslab/yaml/Tag.scala, core/shared/src/main/scala/org/virtuslab/yaml/internal/load/compose/Composer.scala, core/shared/src/test/scala/org/virtuslab/yaml/parser/ScalarSuite.scala, core/shared/src/test/scala/org/virtuslab/yaml/parser/SequenceSuite.scala
Yaml values of the form `"bool"` or `"123"` or other quoted strings will not be interpreted as `java.lang.Boolean` or `java.lang.Integer`.
This fixes Issue #220
=> Issue #220 - do not convert quoted strings into other primitive types

core/shared/src/main/scala-3/org/virtuslab/yaml/YamlDecoderCrossCompat.scala, core/shared/src/test/scala-3/org/virtuslab/yaml/decoder/DecoderSuite.scala
Implicitly parses a nonexistent key as None in case of key type is Option[_]
Fix #203
=> Parses a nonexistent key as None

README.md
Linking scala-yaml/ lands the user at the API index, where one can easily index that there is a "Docs" button which is the guide. Linking to scala-yaml/docs/ instead, links to the "Docs" instead.
=> README: improve link to guide

core/shared/src/main/scala/org/virtuslab/yaml/YamlDecoder.scala, core/shared/src/test/scala-3/org/virtuslab/yaml/decoder/DecoderSuite.scala
Use java.lang.Integer.decode which handles other radices besides 10
Also remove `_` from the number string
=> Fix parsing numbers

core/shared/src/main/scala/org/virtuslab/yaml/YamlDecoder.scala, core/shared/src/test/scala-3/org/virtuslab/yaml/decoder/DecoderErrorsSuite.scala
continuation of https://github.com/VirtusLab/scala-yaml/pull/299
=> Reuse the existing decoders

core/shared/src/main/scala-3/org/virtuslab/yaml/YamlDecoderCrossCompat.scala, core/shared/src/main/scala/org/virtuslab/yaml/YamlDecoder.scala, core/shared/src/main/scala/org/virtuslab/yaml/YamlError.scala, core/shared/src/main/scala/org/virtuslab/yaml/internal/load/parse/ParserImpl.scala, core/shared/src/test/scala-3/org/virtuslab/yaml/ConstructSuite.scala, core/shared/src/test/scala/org/virtuslab/yaml/BaseYamlSuite.scala, core/shared/src/test/scala/org/virtuslab/yaml/parser/ParserSuite.scala
By providing the `ParseError`, `ConstructError` and `ScannerError` the original information that caused the error, an end user can use it for better diagnostics down the line.
Supersedes #271
=> Improve YamlError ADT

core/shared/src/main/scala/org/virtuslab/yaml/internal/load/reader/token/ScalarStyle.scala, core/shared/src/test/scala-3/org/virtuslab/yaml/decoder/DecoderSuite.scala, core/shared/src/test/scala/org/virtuslab/yaml/parser/ScalarSuite.scala
This change fixes #281 buuuut there's a bunch of tests that fail now, like:
```
=> Diff (- obtained, + expected)
Scalar(
-      value = """# The ∙
-CRARG
-# We
-""",
+      value = "# The \\nCRARG\\n# We\\n",
style = Literal(),
```
```
=> Diff (- obtained, + expected)
Scalar(
-      value = """-----BEGIN CERTIFICATE-----
-0MTk0MVoXDenkKThvP7IS9q
-+Dzv5hG392KWh5f8xJNs4LbZyl901MeReiLrPH3w=
------END CERTIFICATE----""",
+      value = "-----BEGIN CERTIFICATE-----\\n0MTk0MVoXDenkKThvP7IS9q\\n+Dzv5hG392KWh5f8xJNs4LbZyl901MeReiLrPH3w=\\n-----END CERTIFICATE----",
style = Literal(),
```
So apparently tests were written **with** the assumption that newlines will end up transformed to escaped newlines: `\n`. I don't think this is correct and I think the author of #281 is correct that we should not …
=> fixed issue 281 but is this correct?

core/shared/src/main/scala/org/virtuslab/yaml/YamlDecoder.scala, core/shared/src/test/scala-3/org/virtuslab/yaml/decoder/DecoderSuite.scala
=> parse all edge cases of ints and floats

core/shared/src/main/scala/org/virtuslab/yaml/YamlEncoder.scala, core/shared/src/test/scala-3/org/virtuslab/yaml/BaseYamlEncoderSuite.scala
=> added escaping of all the non-printable chars as required by spec

core/shared/src/main/scala-3/org/virtuslab/yaml/YamlDecoderCrossCompat.scala, core/shared/src/test/scala-3/org/virtuslab/yaml/decoder/DecoderSuite.scala
had to go from dumb mirrors to a full blown macro for products but hey, mirrors do not expose default params
closes #215
=> added handling for default parameters

core/shared/src/main/scala/org/virtuslab/yaml/Tag.scala, core/shared/src/main/scala/org/virtuslab/yaml/YamlDecoder.scala, core/shared/src/test/scala-3/org/virtuslab/yaml/decoder/DecoderSuite.scala
https://yaml.org/spec/1.2.2/#1032-tag-resolution
https://scastie.scala-lang.org/9DqmGdYWQwWA9OUmjqjbCg
Relates to
* https://github.com/VirtusLab/scala-yaml/issues/314
* https://github.com/VirtusLab/scala-yaml/pull/322
/cc @lbialy @OndrejSpanel
=> Fix YamlDecoder and NaN tag
